version: "3.9"
services:
  mongo1:
    restart: always
    hostname: mongo1
    image: mongo:5
    container_name: mongo1
    ports:
      - 27017:27017
    networks:
      - cluster
    volumes:
      - data1:/data/db
      - ./script.sh:/script.sh
      - ./key:/key
    command: ["bash", "-c","/script.sh"]


  mongo2:
    hostname: mongo2
    restart: always
    image: mongo:5
    container_name: mongo2
    ports:
      - 27018:27017
    networks:
      - cluster
    volumes:
      - data2:/data/db
      - ./script.sh:/script.sh
      - ./key:/key
    command: ["bash", "-c","/script.sh"]


  mongo3:
    hostname: mongo3
    restart: always
    image: mongo:5
    container_name: mongo3
    ports:
      - 27019:27017
    networks:
      - cluster
    volumes:
      - data3:/data/db
      - ./script.sh:/script.sh
      - ./key:/key
    command: ["bash", "-c","/script.sh"]


  setup:
    hostname: setup
    image: mongo:5
    container_name: setup
    ports:
      - 27020:27017
    networks:
      - cluster
    volumes:
      - ./init.sh:/init.sh
      - ./key:/key
    environment:
      user: ${user}
      pass: ${pass}
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    command: ["bash","-c","/init.sh"]
    secrets:
      - mysecret
  
  mongo-express:
    image: mongo-express
    depends_on:
      - setup
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - cluster
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${user}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${pass}
      ME_CONFIG_MONGODB_SERVER: "mongo1,mongo2,mongo3"
    secrets:
      - mysecret

  yolov5:
    depends_on:
      - setup
    image: muhammadqadora/yolov5:1.4
    container_name: yolov5
    hostname: yolov5
    networks:
      - cluster
    ports:
      - 4000:4000
    environment:
      BUCKET_NAME: ${bucket_name}
      MONGO_USER: ${user}
      MONGO_PASS: ${pass}
      CONNECTION_STRING: ${connection_string}
      AWS_ACCESS_KEY_ID: ${aws_access_key_id}
      AWS_SECRET_ACCESS_KEY: ${aws_secret_access_key}
    secrets:
      - mysecret


  polybot:
    depends_on:
      - yolov5
    image: muhammadqadora/polybot
    container_name: polybot
    hostname: polybot
    networks:
      - cluster
    ports:
      - 8443:8443
    environment:
      AWS_ACCESS_KEY_ID: ${aws_access_key_id}
      AWS_SECRET_ACCESS_KEY: ${aws_secret_access_key}
      TELEGRAM_TOKEN: ${telegram_token}
      TELEGRAM_APP_URL: ${ngrok_url}
      YOLO_URL: ${yolo_url}
      BUCKET_NAME: ${bucket_name}
secrets:
  mysecret:
    file: .env
networks:
  cluster:

volumes:
  data1:
  data2:
  data3: