version: "3.9"
services:
  mongo1:
    restart: always
    hostname: mongo1
    image: mongo:5
    container_name: mongo1
    ports:
      - 27017:27017
    networks:
      - cluster
    volumes:
      - data1:/data/db
      - ./script.sh:/script.sh
      - ./key:/key
    command: ["bash", "-c","/script.sh"]


  mongo2:
    hostname: mongo2
    restart: always
    image: mongo:5
    container_name: mongo2
    ports:
      - 27018:27017
    networks:
      - cluster
    volumes:
      - data2:/data/db
      - ./script.sh:/script.sh
      - ./key:/key
    command: ["bash", "-c","/script.sh"]


  mongo3:
    hostname: mongo3
    restart: always
    image: mongo:5
    container_name: mongo3
    ports:
      - 27019:27017
    networks:
      - cluster
    volumes:
      - data3:/data/db
      - ./script.sh:/script.sh
      - ./key:/key
    command: ["bash", "-c","/script.sh"]


  setup:
    hostname: setup
    image: mongo:5
    container_name: setup
    ports:
      - 27020:27017
    networks:
      - cluster
    volumes:
      - ./script.sh:/script.sh
      - ./init.sh:/init.sh
      - ./key:/key
    environment:
      user: ${login}
      pass: ${login}
    depends_on:
      - mongo1
      - mongo2
    command: ["bash","-c","/init.sh"]
  
  mongo-express:
    image: mongo-express
    depends_on:
      - setup
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - cluster
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${login}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${login}
      ME_CONFIG_MONGODB_SERVER: "mongo1,mongo2,mongo3"

networks:
  cluster:

volumes:
  data1:
  data2:
  data3: